title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-feed
  - jekyll-archives


url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
